# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip;
        pip3 install -r requirements.txt;
        pip install pyinstaller
    - name: build
      run: |
        pyinstaller --onefile --noconsole  -n  temp.exe main.py 
    - name: Upload the package
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/') && github.event_name == 'push'
      with:
          files: |
            /home/runner/work/toolbox/toolbox/dist/temp.exe

